package asd.project.domain.event;

public enum EventType {
  NETWORK_GAME_STATE,
  NETWORK_MESSAGE,
  NETWORK_GAME_START,
  NETWORK_CONNECTION_CHANGE,
  NETWORK_SET_SUBHOST_LIST,
  NETWORK_CONNECTION_DISCONNECT,
  NETWORK_INTERNET_CONNECTION_ISSUES,
  NETWORK_HOST_DISCONNECT,
  NETWORK_HOST_FOUND,
  NETWORK_SET_ENTITY_CONFIG,
  NETWORK_REPLACE_PLAYER,
  NETWORK_GAME_PAUSE,
  NETWORK_DISCONNECT_CLIENT,
  NETWORK_SEND_MESSAGE_ISSUE,
  UI_COMMAND,
  UI_MESSAGE,
  STORAGE_GET_SUBHOST_LIST
}
